### PR TITLE
New Example Notebook: Quantitative and Visual Comparisons of Different Sampling Algorithms with Fast Food

### PR DESCRIPTION
**Pull request by JacksonBurns**
This PR is related to #79 and adds a new Jupyter notebook example to the repository. This notebook uses the burger king menu as a dataset and does a visual example of how the different sampling algorithms will partition the data. Quantitative comparisons will be baked in as well.

The dataset was chosen for its simplicity - the features are the grams of each macronutrient in the various menu items at burger king with the target being the total number of calories. The underlying correlation is both simple and known with the idea being that a well-trained model should be able to learn it. The low dimensionality of this dataset, as well as the physical nature of it, makes it easy to visualize and understand.

The plots created in this notebook will be useful visualizations for any future presentations, the README, etc.

### CODE REVIEW

**Comment by JacksonBurns** [comment]
@kspieks I made some minor revisions to how the modeling approach is presented. If you could take a look at (1) the notebook as a whole for clarity/correctness (2) Part 3, Interpolation to see where we could potentially add some citations to points people toward why train/val/test sampling is a good idea and (3) Part 1, Choosing and Interpolation Algorithm for citations about why extrapolation is a more relevant question, particularly in discovery

**Comment by JacksonBurns** [comment]
This notebook/rendered html would be a good candidate for submission [here](https://support.access-ci.org/resources) as well.

**Review by kspieks — APPROVED** [review]
Thanks for this awesome notebook! I read through it and ran the cells. I thought the explanations and examples were very clear. The diff is too large to view online (and thus make comments) so I pushed a few minor updates. I'm happy to continue discussing if my changes are unclear, but feel free to merge after reviewing the updated notebook. 

I'd potentially suggest moving the notebook and csv to it's own folder within `examples` but I don't feel strongly about how it's organized.

I added some references to textbooks to Part 3 that have sections explaining why train, val, and test data is needed for ML. I also added some references to literature to Part 1 that discuss the importance of evaluating models with extrapolation tasks so we can better measure their utility for materials discovery.

**Comment by JacksonBurns** [comment]
Thanks for the review and updates! I will rebase and make the change to the organization in the directory to match the rest of the repository and then merge - thanks!

**Pull request merged**
